/*
 Navicat Premium Data Transfer

 Source Server         : localhost
 Source Server Type    : MySQL
 Source Server Version : 50721
 Source Host           : localhost:3306
 Source Schema         : codeigniter_database_backup

 Target Server Type    : MySQL
 Target Server Version : 50721
 File Encoding         : 65001

 Date: 03/09/2018 11:47:47
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for ilceler
-- ----------------------------
DROP TABLE IF EXISTS `ilceler`;
CREATE TABLE `ilceler` (
  `ilce_id` smallint(5) unsigned NOT NULL AUTO_INCREMENT,
  `il_id_fk` tinyint(3) unsigned NOT NULL,
  `ilce_adi` char(40) NOT NULL,
  PRIMARY KEY (`ilce_id`),
  UNIQUE KEY `ilce_id` (`ilce_id`) USING BTREE,
  KEY `il_id_fk` (`il_id_fk`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=968 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of ilceler
-- ----------------------------
BEGIN;
INSERT INTO `ilceler` VALUES (1, 1, 'Seyhan');
INSERT INTO `ilceler` VALUES (2, 1, 'Ceyhan');
INSERT INTO `ilceler` VALUES (3, 1, 'Feke');
INSERT INTO `ilceler` VALUES (4, 1, 'Karaisalı');
INSERT INTO `ilceler` VALUES (5, 1, 'Karataş');
INSERT INTO `ilceler` VALUES (6, 1, 'Kozan');
INSERT INTO `ilceler` VALUES (7, 1, 'Pozantı');
INSERT INTO `ilceler` VALUES (8, 1, 'Saimbeyli');
INSERT INTO `ilceler` VALUES (9, 1, 'Tufanbeyli');
INSERT INTO `ilceler` VALUES (10, 1, 'Yumurtalık');
INSERT INTO `ilceler` VALUES (11, 1, 'Yüreğir');
INSERT INTO `ilceler` VALUES (12, 1, 'Aladağ');
INSERT INTO `ilceler` VALUES (13, 1, 'İmamoğlu');
INSERT INTO `ilceler` VALUES (14, 1, 'Sarıçam');
INSERT INTO `ilceler` VALUES (15, 1, 'Çukurova');
INSERT INTO `ilceler` VALUES (16, 2, 'Adıyaman Merkez');
INSERT INTO `ilceler` VALUES (17, 2, 'Besni');
INSERT INTO `ilceler` VALUES (18, 2, 'Çelikhan');
INSERT INTO `ilceler` VALUES (19, 2, 'Gerger');
INSERT INTO `ilceler` VALUES (20, 2, 'Gölbaşı / Adıyaman');
INSERT INTO `ilceler` VALUES (21, 2, 'Kahta');
INSERT INTO `ilceler` VALUES (22, 2, 'Samsat');
INSERT INTO `ilceler` VALUES (23, 2, 'Sincik');
INSERT INTO `ilceler` VALUES (24, 2, 'Tut');
INSERT INTO `ilceler` VALUES (25, 3, 'Afyonkarahisar Merkez');
INSERT INTO `ilceler` VALUES (26, 3, 'Bolvadin');
INSERT INTO `ilceler` VALUES (27, 3, 'Çay');
INSERT INTO `ilceler` VALUES (28, 3, 'Dazkırı');
INSERT INTO `ilceler` VALUES (29, 3, 'Dinar');
INSERT INTO `ilceler` VALUES (30, 3, 'Emirdağ');
INSERT INTO `ilceler` VALUES (31, 3, 'İhsaniye');
INSERT INTO `ilceler` VALUES (32, 3, 'Sandıklı');
INSERT INTO `ilceler` VALUES (33, 3, 'Sinanpaşa');
INSERT INTO `ilceler` VALUES (34, 3, 'Sultandağı');
INSERT INTO `ilceler` VALUES (35, 3, 'Şuhut');
INSERT INTO `ilceler` VALUES (36, 3, 'Başmakçı');
INSERT INTO `ilceler` VALUES (37, 3, 'Bayat / Afyonkarahisar');
INSERT INTO `ilceler` VALUES (38, 3, 'İscehisar');
INSERT INTO `ilceler` VALUES (39, 3, 'Çobanlar');
INSERT INTO `ilceler` VALUES (40, 3, 'Evciler');
INSERT INTO `ilceler` VALUES (41, 3, 'Hocalar');
INSERT INTO `ilceler` VALUES (42, 3, 'Kızılören');
INSERT INTO `ilceler` VALUES (43, 4, 'Ağrı Merkez');
INSERT INTO `ilceler` VALUES (44, 4, 'Diyadin');
INSERT INTO `ilceler` VALUES (45, 4, 'Doğubayazıt');
INSERT INTO `ilceler` VALUES (46, 4, 'Eleşkirt');
INSERT INTO `ilceler` VALUES (47, 4, 'Hamur');
INSERT INTO `ilceler` VALUES (48, 4, 'Patnos');
INSERT INTO `ilceler` VALUES (49, 4, 'Taşlıçay');
INSERT INTO `ilceler` VALUES (50, 4, 'Tutak');
INSERT INTO `ilceler` VALUES (51, 5, 'Amasya Merkez');
INSERT INTO `ilceler` VALUES (52, 5, 'Göynücek');
INSERT INTO `ilceler` VALUES (53, 5, 'Gümüşhacıköy');
INSERT INTO `ilceler` VALUES (54, 5, 'Merzifon');
INSERT INTO `ilceler` VALUES (55, 5, 'Suluova');
INSERT INTO `ilceler` VALUES (56, 5, 'Taşova');
INSERT INTO `ilceler` VALUES (57, 5, 'Hamamözü');
INSERT INTO `ilceler` VALUES (58, 6, 'Altındağ');
INSERT INTO `ilceler` VALUES (59, 6, 'Ayaş');
INSERT INTO `ilceler` VALUES (60, 6, 'Bala');
INSERT INTO `ilceler` VALUES (61, 6, 'Beypazarı');
INSERT INTO `ilceler` VALUES (62, 6, 'Çamlıdere');
INSERT INTO `ilceler` VALUES (63, 6, 'Çankaya');
INSERT INTO `ilceler` VALUES (64, 6, 'Çubuk');
INSERT INTO `ilceler` VALUES (65, 6, 'Elmadağ');
INSERT INTO `ilceler` VALUES (66, 6, 'Güdül');
INSERT INTO `ilceler` VALUES (67, 6, 'Haymana');
INSERT INTO `ilceler` VALUES (68, 6, 'Kalecik');
INSERT INTO `ilceler` VALUES (69, 6, 'Kızılcahamam');
INSERT INTO `ilceler` VALUES (70, 6, 'Nallıhan');
INSERT INTO `ilceler` VALUES (71, 6, 'Polatlı');
INSERT INTO `ilceler` VALUES (72, 6, 'Şereflikoçhisar');
INSERT INTO `ilceler` VALUES (73, 6, 'Yenimahalle');
INSERT INTO `ilceler` VALUES (74, 6, 'Gölbaşı / Ankara');
INSERT INTO `ilceler` VALUES (75, 6, 'Keçiören');
INSERT INTO `ilceler` VALUES (76, 6, 'Mamak');
INSERT INTO `ilceler` VALUES (77, 6, 'Sincan');
INSERT INTO `ilceler` VALUES (78, 6, 'Kazan');
INSERT INTO `ilceler` VALUES (79, 6, 'Akyurt');
INSERT INTO `ilceler` VALUES (80, 6, 'Etimesgut');
INSERT INTO `ilceler` VALUES (81, 6, 'Evren');
INSERT INTO `ilceler` VALUES (82, 6, 'Pursaklar');
INSERT INTO `ilceler` VALUES (83, 7, 'Akseki');
INSERT INTO `ilceler` VALUES (84, 7, 'Alanya');
INSERT INTO `ilceler` VALUES (85, 7, 'Elmalı');
INSERT INTO `ilceler` VALUES (86, 7, 'Finike');
INSERT INTO `ilceler` VALUES (87, 7, 'Gazipaşa');
INSERT INTO `ilceler` VALUES (88, 7, 'Gündoğmuş');
INSERT INTO `ilceler` VALUES (89, 7, 'Kaş');
INSERT INTO `ilceler` VALUES (90, 7, 'Korkuteli');
INSERT INTO `ilceler` VALUES (91, 7, 'Kumluca');
INSERT INTO `ilceler` VALUES (92, 7, 'Manavgat');
INSERT INTO `ilceler` VALUES (93, 7, 'Serik');
INSERT INTO `ilceler` VALUES (94, 7, 'Demre');
INSERT INTO `ilceler` VALUES (95, 7, 'İbradı');
INSERT INTO `ilceler` VALUES (96, 7, 'Kemer / Antalya');
INSERT INTO `ilceler` VALUES (97, 7, 'Aksu / Antalya');
INSERT INTO `ilceler` VALUES (98, 7, 'Döşemealtı');
INSERT INTO `ilceler` VALUES (99, 7, 'Kepez');
INSERT INTO `ilceler` VALUES (100, 7, 'Konyaaltı');
INSERT INTO `ilceler` VALUES (101, 7, 'Muratpaşa');
INSERT INTO `ilceler` VALUES (102, 8, 'Ardanuç');
INSERT INTO `ilceler` VALUES (103, 8, 'Arhavi');
INSERT INTO `ilceler` VALUES (104, 8, 'Artvin Merkez');
INSERT INTO `ilceler` VALUES (105, 8, 'Borçka');
INSERT INTO `ilceler` VALUES (106, 8, 'Hopa');
INSERT INTO `ilceler` VALUES (107, 8, 'Şavşat');
INSERT INTO `ilceler` VALUES (108, 8, 'Yusufeli');
INSERT INTO `ilceler` VALUES (109, 8, 'Murgul');
INSERT INTO `ilceler` VALUES (110, 9, 'Bozdoğan');
INSERT INTO `ilceler` VALUES (111, 9, 'Çine');
INSERT INTO `ilceler` VALUES (112, 9, 'Germencik');
INSERT INTO `ilceler` VALUES (113, 9, 'Karacasu');
INSERT INTO `ilceler` VALUES (114, 9, 'Koçarlı');
INSERT INTO `ilceler` VALUES (115, 9, 'Kuşadası');
INSERT INTO `ilceler` VALUES (116, 9, 'Kuyucak');
INSERT INTO `ilceler` VALUES (117, 9, 'Nazilli');
INSERT INTO `ilceler` VALUES (118, 9, 'Söke');
INSERT INTO `ilceler` VALUES (119, 9, 'Sultanhisar');
INSERT INTO `ilceler` VALUES (120, 9, 'Yenipazar / Aydın');
INSERT INTO `ilceler` VALUES (121, 9, 'Buharkent');
INSERT INTO `ilceler` VALUES (122, 9, 'İncirliova');
INSERT INTO `ilceler` VALUES (123, 9, 'Karpuzlu');
INSERT INTO `ilceler` VALUES (124, 9, 'Köşk');
INSERT INTO `ilceler` VALUES (125, 9, 'Didim');
INSERT INTO `ilceler` VALUES (126, 9, 'Efeler');
INSERT INTO `ilceler` VALUES (127, 10, 'Ayvalık');
INSERT INTO `ilceler` VALUES (128, 10, 'Balya');
INSERT INTO `ilceler` VALUES (129, 10, 'Bandırma');
INSERT INTO `ilceler` VALUES (130, 10, 'Bigadiç');
INSERT INTO `ilceler` VALUES (131, 10, 'Burhaniye');
INSERT INTO `ilceler` VALUES (132, 10, 'Dursunbey');
INSERT INTO `ilceler` VALUES (133, 10, 'Edremit / Balıkesir');
INSERT INTO `ilceler` VALUES (134, 10, 'Erdek');
INSERT INTO `ilceler` VALUES (135, 10, 'Gönen / Balıkesir');
INSERT INTO `ilceler` VALUES (136, 10, 'Havran');
INSERT INTO `ilceler` VALUES (137, 10, 'İvrindi');
INSERT INTO `ilceler` VALUES (138, 10, 'Kepsut');
INSERT INTO `ilceler` VALUES (139, 10, 'Manyas');
INSERT INTO `ilceler` VALUES (140, 10, 'Savaştepe');
INSERT INTO `ilceler` VALUES (141, 10, 'Sındırgı');
INSERT INTO `ilceler` VALUES (142, 10, 'Susurluk');
INSERT INTO `ilceler` VALUES (143, 10, 'Marmara');
INSERT INTO `ilceler` VALUES (144, 10, 'Gömeç');
INSERT INTO `ilceler` VALUES (145, 10, 'Altıeylül');
INSERT INTO `ilceler` VALUES (146, 10, 'Karesi');
INSERT INTO `ilceler` VALUES (147, 11, 'Bilecik Merkez');
INSERT INTO `ilceler` VALUES (148, 11, 'Bozüyük');
INSERT INTO `ilceler` VALUES (149, 11, 'Gölpazarı');
INSERT INTO `ilceler` VALUES (150, 11, 'Osmaneli');
INSERT INTO `ilceler` VALUES (151, 11, 'Pazaryeri');
INSERT INTO `ilceler` VALUES (152, 11, 'Söğüt');
INSERT INTO `ilceler` VALUES (153, 11, 'Yenipazar / Bilecik');
INSERT INTO `ilceler` VALUES (154, 11, 'İnhisar');
INSERT INTO `ilceler` VALUES (155, 12, 'Bingöl Merkez');
INSERT INTO `ilceler` VALUES (156, 12, 'Genç');
INSERT INTO `ilceler` VALUES (157, 12, 'Karlıova');
INSERT INTO `ilceler` VALUES (158, 12, 'Kiğı');
INSERT INTO `ilceler` VALUES (159, 12, 'Solhan');
INSERT INTO `ilceler` VALUES (160, 12, 'Adaklı');
INSERT INTO `ilceler` VALUES (161, 12, 'Yayladere');
INSERT INTO `ilceler` VALUES (162, 12, 'Yedisu');
INSERT INTO `ilceler` VALUES (163, 13, 'Adilcevaz');
INSERT INTO `ilceler` VALUES (164, 13, 'Ahlat');
INSERT INTO `ilceler` VALUES (165, 13, 'Bitlis Merkez');
INSERT INTO `ilceler` VALUES (166, 13, 'Hizan');
INSERT INTO `ilceler` VALUES (167, 13, 'Mutki');
INSERT INTO `ilceler` VALUES (168, 13, 'Tatvan');
INSERT INTO `ilceler` VALUES (169, 13, 'Güroymak');
INSERT INTO `ilceler` VALUES (170, 14, 'Bolu Merkez');
INSERT INTO `ilceler` VALUES (171, 14, 'Gerede');
INSERT INTO `ilceler` VALUES (172, 14, 'Göynük');
INSERT INTO `ilceler` VALUES (173, 14, 'Kıbrıscık');
INSERT INTO `ilceler` VALUES (174, 14, 'Mengen');
INSERT INTO `ilceler` VALUES (175, 14, 'Mudurnu');
INSERT INTO `ilceler` VALUES (176, 14, 'Seben');
INSERT INTO `ilceler` VALUES (177, 14, 'Dörtdivan');
INSERT INTO `ilceler` VALUES (178, 14, 'Yeniçağa');
INSERT INTO `ilceler` VALUES (179, 15, 'Ağlasun');
INSERT INTO `ilceler` VALUES (180, 15, 'Bucak');
INSERT INTO `ilceler` VALUES (181, 15, 'Burdur Merkez');
INSERT INTO `ilceler` VALUES (182, 15, 'Gölhisar');
INSERT INTO `ilceler` VALUES (183, 15, 'Tefenni');
INSERT INTO `ilceler` VALUES (184, 15, 'Yeşilova');
INSERT INTO `ilceler` VALUES (185, 15, 'Karamanlı');
INSERT INTO `ilceler` VALUES (186, 15, 'Kemer / Burdur');
INSERT INTO `ilceler` VALUES (187, 15, 'Altınyayla / Burdur');
INSERT INTO `ilceler` VALUES (188, 15, 'Çavdır');
INSERT INTO `ilceler` VALUES (189, 15, 'Çeltikçi');
INSERT INTO `ilceler` VALUES (190, 16, 'Gemlik');
INSERT INTO `ilceler` VALUES (191, 16, 'İnegöl');
INSERT INTO `ilceler` VALUES (192, 16, 'İznik');
INSERT INTO `ilceler` VALUES (193, 16, 'Karacabey');
INSERT INTO `ilceler` VALUES (194, 16, 'Keles');
INSERT INTO `ilceler` VALUES (195, 16, 'Mudanya');
INSERT INTO `ilceler` VALUES (196, 16, 'Mustafakemalpaşa');
INSERT INTO `ilceler` VALUES (197, 16, 'Orhaneli');
INSERT INTO `ilceler` VALUES (198, 16, 'Orhangazi');
INSERT INTO `ilceler` VALUES (199, 16, 'Yenişehir / Bursa');
INSERT INTO `ilceler` VALUES (200, 16, 'Büyükorhan');
INSERT INTO `ilceler` VALUES (201, 16, 'Harmancık');
INSERT INTO `ilceler` VALUES (202, 16, 'Nilüfer');
INSERT INTO `ilceler` VALUES (203, 16, 'Osmangazi');
INSERT INTO `ilceler` VALUES (204, 16, 'Yıldırım');
INSERT INTO `ilceler` VALUES (205, 16, 'Gürsu');
INSERT INTO `ilceler` VALUES (206, 16, 'Kestel');
INSERT INTO `ilceler` VALUES (207, 17, 'Ayvacık / Çanakkale');
INSERT INTO `ilceler` VALUES (208, 17, 'Bayramiç');
INSERT INTO `ilceler` VALUES (209, 17, 'Biga');
INSERT INTO `ilceler` VALUES (210, 17, 'Bozcaada');
INSERT INTO `ilceler` VALUES (211, 17, 'Çan');
INSERT INTO `ilceler` VALUES (212, 17, 'Çanakkale Merkez');
INSERT INTO `ilceler` VALUES (213, 17, 'Eceabat');
INSERT INTO `ilceler` VALUES (214, 17, 'Ezine');
INSERT INTO `ilceler` VALUES (215, 17, 'Gelibolu');
INSERT INTO `ilceler` VALUES (216, 17, 'Gökçeada');
INSERT INTO `ilceler` VALUES (217, 17, 'Lapseki');
INSERT INTO `ilceler` VALUES (218, 17, 'Yenice / Çanakkale');
INSERT INTO `ilceler` VALUES (219, 18, 'Çankırı Merkez');
INSERT INTO `ilceler` VALUES (220, 18, 'Çerkeş');
INSERT INTO `ilceler` VALUES (221, 18, 'Eldivan');
INSERT INTO `ilceler` VALUES (222, 18, 'Ilgaz');
INSERT INTO `ilceler` VALUES (223, 18, 'Kurşunlu');
INSERT INTO `ilceler` VALUES (224, 18, 'Orta');
INSERT INTO `ilceler` VALUES (225, 18, 'Şabanözü');
INSERT INTO `ilceler` VALUES (226, 18, 'Yapraklı');
INSERT INTO `ilceler` VALUES (227, 18, 'Atkaracalar');
INSERT INTO `ilceler` VALUES (228, 18, 'Kızılırmak');
INSERT INTO `ilceler` VALUES (229, 18, 'Bayramören');
INSERT INTO `ilceler` VALUES (230, 18, 'Korgun');
INSERT INTO `ilceler` VALUES (231, 19, 'Alaca');
INSERT INTO `ilceler` VALUES (232, 19, 'Bayat / Çorum');
INSERT INTO `ilceler` VALUES (233, 19, 'Çorum Merkez');
INSERT INTO `ilceler` VALUES (234, 19, 'İskilip');
INSERT INTO `ilceler` VALUES (235, 19, 'Kargı');
INSERT INTO `ilceler` VALUES (236, 19, 'Mecitözü');
INSERT INTO `ilceler` VALUES (237, 19, 'Ortaköy / Çorum');
INSERT INTO `ilceler` VALUES (238, 19, 'Osmancık');
INSERT INTO `ilceler` VALUES (239, 19, 'Sungurlu');
INSERT INTO `ilceler` VALUES (240, 19, 'Boğazkale');
INSERT INTO `ilceler` VALUES (241, 19, 'Uğurludağ');
INSERT INTO `ilceler` VALUES (242, 19, 'Dodurga');
INSERT INTO `ilceler` VALUES (243, 19, 'Laçin');
INSERT INTO `ilceler` VALUES (244, 19, 'Oğuzlar');
INSERT INTO `ilceler` VALUES (245, 20, 'Acıpayam');
INSERT INTO `ilceler` VALUES (246, 20, 'Buldan');
INSERT INTO `ilceler` VALUES (247, 20, 'Çal');
INSERT INTO `ilceler` VALUES (248, 20, 'Çameli');
INSERT INTO `ilceler` VALUES (249, 20, 'Çardak');
INSERT INTO `ilceler` VALUES (250, 20, 'Çivril');
INSERT INTO `ilceler` VALUES (251, 20, 'Güney');
INSERT INTO `ilceler` VALUES (252, 20, 'Kale / Denizli');
INSERT INTO `ilceler` VALUES (253, 20, 'Sarayköy');
INSERT INTO `ilceler` VALUES (254, 20, 'Tavas');
INSERT INTO `ilceler` VALUES (255, 20, 'Babadağ');
INSERT INTO `ilceler` VALUES (256, 20, 'Bekilli');
INSERT INTO `ilceler` VALUES (257, 20, 'Honaz');
INSERT INTO `ilceler` VALUES (258, 20, 'Serinhisar');
INSERT INTO `ilceler` VALUES (259, 20, 'Pamukkale');
INSERT INTO `ilceler` VALUES (260, 20, 'Baklan');
INSERT INTO `ilceler` VALUES (261, 20, 'Beyağaç');
INSERT INTO `ilceler` VALUES (262, 20, 'Bozkurt / Denizli');
INSERT INTO `ilceler` VALUES (263, 20, 'Merkezefendi');
INSERT INTO `ilceler` VALUES (264, 21, 'Bismil');
INSERT INTO `ilceler` VALUES (265, 21, 'Çermik');
INSERT INTO `ilceler` VALUES (266, 21, 'Çınar');
INSERT INTO `ilceler` VALUES (267, 21, 'Çüngüş');
INSERT INTO `ilceler` VALUES (268, 21, 'Dicle');
INSERT INTO `ilceler` VALUES (269, 21, 'Ergani');
INSERT INTO `ilceler` VALUES (270, 21, 'Hani');
INSERT INTO `ilceler` VALUES (271, 21, 'Hazro');
INSERT INTO `ilceler` VALUES (272, 21, 'Kulp');
INSERT INTO `ilceler` VALUES (273, 21, 'Lice');
INSERT INTO `ilceler` VALUES (274, 21, 'Silvan');
INSERT INTO `ilceler` VALUES (275, 21, 'Eğil');
INSERT INTO `ilceler` VALUES (276, 21, 'Kocaköy');
INSERT INTO `ilceler` VALUES (277, 21, 'Bağlar');
INSERT INTO `ilceler` VALUES (278, 21, 'Kayapınar');
INSERT INTO `ilceler` VALUES (279, 21, 'Sur');
INSERT INTO `ilceler` VALUES (280, 21, 'Yenişehir / Diyarbakır');
INSERT INTO `ilceler` VALUES (281, 22, 'Edirne Merkez');
INSERT INTO `ilceler` VALUES (282, 22, 'Enez');
INSERT INTO `ilceler` VALUES (283, 22, 'Havsa');
INSERT INTO `ilceler` VALUES (284, 22, 'İpsala');
INSERT INTO `ilceler` VALUES (285, 22, 'Keşan');
INSERT INTO `ilceler` VALUES (286, 22, 'Lalapaşa');
INSERT INTO `ilceler` VALUES (287, 22, 'Meriç');
INSERT INTO `ilceler` VALUES (288, 22, 'Uzunköprü');
INSERT INTO `ilceler` VALUES (289, 22, 'Süloğlu');
INSERT INTO `ilceler` VALUES (290, 23, 'Ağın');
INSERT INTO `ilceler` VALUES (291, 23, 'Baskil');
INSERT INTO `ilceler` VALUES (292, 23, 'Elazığ Merkez');
INSERT INTO `ilceler` VALUES (293, 23, 'Karakoçan');
INSERT INTO `ilceler` VALUES (294, 23, 'Keban');
INSERT INTO `ilceler` VALUES (295, 23, 'Maden');
INSERT INTO `ilceler` VALUES (296, 23, 'Palu');
INSERT INTO `ilceler` VALUES (297, 23, 'Sivrice');
INSERT INTO `ilceler` VALUES (298, 23, 'Arıcak');
INSERT INTO `ilceler` VALUES (299, 23, 'Kovancılar');
INSERT INTO `ilceler` VALUES (300, 23, 'Alacakaya');
INSERT INTO `ilceler` VALUES (301, 24, 'Çayırlı');
INSERT INTO `ilceler` VALUES (302, 24, 'Erzincan Merkez');
INSERT INTO `ilceler` VALUES (303, 24, 'İliç');
INSERT INTO `ilceler` VALUES (304, 24, 'Kemah');
INSERT INTO `ilceler` VALUES (305, 24, 'Kemaliye');
INSERT INTO `ilceler` VALUES (306, 24, 'Refahiye');
INSERT INTO `ilceler` VALUES (307, 24, 'Tercan');
INSERT INTO `ilceler` VALUES (308, 24, 'Üzümlü');
INSERT INTO `ilceler` VALUES (309, 24, 'Otlukbeli');
INSERT INTO `ilceler` VALUES (310, 25, 'Aşkale');
INSERT INTO `ilceler` VALUES (311, 25, 'Çat');
INSERT INTO `ilceler` VALUES (312, 25, 'Hınıs');
INSERT INTO `ilceler` VALUES (313, 25, 'Horasan');
INSERT INTO `ilceler` VALUES (314, 25, 'İspir');
INSERT INTO `ilceler` VALUES (315, 25, 'Karayazı');
INSERT INTO `ilceler` VALUES (316, 25, 'Narman');
INSERT INTO `ilceler` VALUES (317, 25, 'Oltu');
INSERT INTO `ilceler` VALUES (318, 25, 'Olur');
INSERT INTO `ilceler` VALUES (319, 25, 'Pasinler');
INSERT INTO `ilceler` VALUES (320, 25, 'Şenkaya');
INSERT INTO `ilceler` VALUES (321, 25, 'Tekman');
INSERT INTO `ilceler` VALUES (322, 25, 'Tortum');
INSERT INTO `ilceler` VALUES (323, 25, 'Karaçoban');
INSERT INTO `ilceler` VALUES (324, 25, 'Uzundere');
INSERT INTO `ilceler` VALUES (325, 25, 'Pazaryolu');
INSERT INTO `ilceler` VALUES (326, 25, 'Aziziye');
INSERT INTO `ilceler` VALUES (327, 25, 'Köprüköy');
INSERT INTO `ilceler` VALUES (328, 25, 'Palandöken');
INSERT INTO `ilceler` VALUES (329, 25, 'Yakutiye');
INSERT INTO `ilceler` VALUES (330, 26, 'Çifteler');
INSERT INTO `ilceler` VALUES (331, 26, 'Mahmudiye');
INSERT INTO `ilceler` VALUES (332, 26, 'Mihalıççık');
INSERT INTO `ilceler` VALUES (333, 26, 'Sarıcakaya');
INSERT INTO `ilceler` VALUES (334, 26, 'Seyitgazi');
INSERT INTO `ilceler` VALUES (335, 26, 'Sivrihisar');
INSERT INTO `ilceler` VALUES (336, 26, 'Alpu');
INSERT INTO `ilceler` VALUES (337, 26, 'Beylikova');
INSERT INTO `ilceler` VALUES (338, 26, 'İnönü');
INSERT INTO `ilceler` VALUES (339, 26, 'Günyüzü');
INSERT INTO `ilceler` VALUES (340, 26, 'Han');
INSERT INTO `ilceler` VALUES (341, 26, 'Mihalgazi');
INSERT INTO `ilceler` VALUES (342, 26, 'Odunpazarı');
INSERT INTO `ilceler` VALUES (343, 26, 'Tepebaşı');
INSERT INTO `ilceler` VALUES (344, 27, 'Araban');
INSERT INTO `ilceler` VALUES (345, 27, 'İslahiye');
INSERT INTO `ilceler` VALUES (346, 27, 'Nizip');
INSERT INTO `ilceler` VALUES (347, 27, 'Oğuzeli');
INSERT INTO `ilceler` VALUES (348, 27, 'Yavuzeli');
INSERT INTO `ilceler` VALUES (349, 27, 'Şahinbey');
INSERT INTO `ilceler` VALUES (350, 27, 'Şehitkamil');
INSERT INTO `ilceler` VALUES (351, 27, 'Karkamış');
INSERT INTO `ilceler` VALUES (352, 27, 'Nurdağı');
INSERT INTO `ilceler` VALUES (353, 28, 'Alucra');
INSERT INTO `ilceler` VALUES (354, 28, 'Bulancak');
INSERT INTO `ilceler` VALUES (355, 28, 'Dereli');
INSERT INTO `ilceler` VALUES (356, 28, 'Espiye');
INSERT INTO `ilceler` VALUES (357, 28, 'Eynesil');
INSERT INTO `ilceler` VALUES (358, 28, 'Giresun Merkez');
INSERT INTO `ilceler` VALUES (359, 28, 'Görele');
INSERT INTO `ilceler` VALUES (360, 28, 'Keşap');
INSERT INTO `ilceler` VALUES (361, 28, 'Şebinkarahisar');
INSERT INTO `ilceler` VALUES (362, 28, 'Tirebolu');
INSERT INTO `ilceler` VALUES (363, 28, 'Piraziz');
INSERT INTO `ilceler` VALUES (364, 28, 'Yağlıdere');
INSERT INTO `ilceler` VALUES (365, 28, 'Çamoluk');
INSERT INTO `ilceler` VALUES (366, 28, 'Çanakçı');
INSERT INTO `ilceler` VALUES (367, 28, 'Doğankent');
INSERT INTO `ilceler` VALUES (368, 28, 'Güce');
INSERT INTO `ilceler` VALUES (369, 29, 'Gümüşhane Merkez');
INSERT INTO `ilceler` VALUES (370, 29, 'Kelkit');
INSERT INTO `ilceler` VALUES (371, 29, 'Şiran');
INSERT INTO `ilceler` VALUES (372, 29, 'Torul');
INSERT INTO `ilceler` VALUES (373, 29, 'Köse');
INSERT INTO `ilceler` VALUES (374, 29, 'Kürtün');
INSERT INTO `ilceler` VALUES (375, 30, 'Çukurca');
INSERT INTO `ilceler` VALUES (376, 30, 'Hakkari Merkez');
INSERT INTO `ilceler` VALUES (377, 30, 'Şemdinli');
INSERT INTO `ilceler` VALUES (378, 30, 'Yüksekova');
INSERT INTO `ilceler` VALUES (379, 31, 'Altınözü');
INSERT INTO `ilceler` VALUES (380, 31, 'Dörtyol');
INSERT INTO `ilceler` VALUES (381, 31, 'Hassa');
INSERT INTO `ilceler` VALUES (382, 31, 'İskenderun');
INSERT INTO `ilceler` VALUES (383, 31, 'Kırıkhan');
INSERT INTO `ilceler` VALUES (384, 31, 'Reyhanlı');
INSERT INTO `ilceler` VALUES (385, 31, 'Samandağ');
INSERT INTO `ilceler` VALUES (386, 31, 'Yayladağı');
INSERT INTO `ilceler` VALUES (387, 31, 'Erzin');
INSERT INTO `ilceler` VALUES (388, 31, 'Belen');
INSERT INTO `ilceler` VALUES (389, 31, 'Kumlu');
INSERT INTO `ilceler` VALUES (390, 31, 'Antakya');
INSERT INTO `ilceler` VALUES (391, 31, 'Arsuz');
INSERT INTO `ilceler` VALUES (392, 31, 'Defne');
INSERT INTO `ilceler` VALUES (393, 31, 'Payas');
INSERT INTO `ilceler` VALUES (394, 32, 'Atabey');
INSERT INTO `ilceler` VALUES (395, 32, 'Eğirdir');
INSERT INTO `ilceler` VALUES (396, 32, 'Gelendost');
INSERT INTO `ilceler` VALUES (397, 32, 'Isparta Merkez');
INSERT INTO `ilceler` VALUES (398, 32, 'Keçiborlu');
INSERT INTO `ilceler` VALUES (399, 32, 'Senirkent');
INSERT INTO `ilceler` VALUES (400, 32, 'Sütçüler');
INSERT INTO `ilceler` VALUES (401, 32, 'Şarkikaraağaç');
INSERT INTO `ilceler` VALUES (402, 32, 'Uluborlu');
INSERT INTO `ilceler` VALUES (403, 32, 'Yalvaç');
INSERT INTO `ilceler` VALUES (404, 32, 'Aksu / Isparta');
INSERT INTO `ilceler` VALUES (405, 32, 'Gönen / Isparta');
INSERT INTO `ilceler` VALUES (406, 32, 'Yenişarbademli');
INSERT INTO `ilceler` VALUES (407, 33, 'Anamur');
INSERT INTO `ilceler` VALUES (408, 33, 'Erdemli');
INSERT INTO `ilceler` VALUES (409, 33, 'Gülnar');
INSERT INTO `ilceler` VALUES (410, 33, 'Mut');
INSERT INTO `ilceler` VALUES (411, 33, 'Silifke');
INSERT INTO `ilceler` VALUES (412, 33, 'Tarsus');
INSERT INTO `ilceler` VALUES (413, 33, 'Aydıncık / Mersin');
INSERT INTO `ilceler` VALUES (414, 33, 'Bozyazı');
INSERT INTO `ilceler` VALUES (415, 33, 'Çamlıyayla');
INSERT INTO `ilceler` VALUES (416, 33, 'Akdeniz');
INSERT INTO `ilceler` VALUES (417, 33, 'Mezitli');
INSERT INTO `ilceler` VALUES (418, 33, 'Toroslar');
INSERT INTO `ilceler` VALUES (419, 33, 'Yenişehir / Mersin');
INSERT INTO `ilceler` VALUES (420, 34, 'Adalar');
INSERT INTO `ilceler` VALUES (421, 34, 'Bakırköy');
INSERT INTO `ilceler` VALUES (422, 34, 'Beşiktaş');
INSERT INTO `ilceler` VALUES (423, 34, 'Beykoz');
INSERT INTO `ilceler` VALUES (424, 34, 'Beyoğlu');
INSERT INTO `ilceler` VALUES (425, 34, 'Çatalca');
INSERT INTO `ilceler` VALUES (426, 34, 'Eyüp');
INSERT INTO `ilceler` VALUES (427, 34, 'Fatih');
INSERT INTO `ilceler` VALUES (428, 34, 'Gaziosmanpaşa');
INSERT INTO `ilceler` VALUES (429, 34, 'Kadıköy');
INSERT INTO `ilceler` VALUES (430, 34, 'Kartal');
INSERT INTO `ilceler` VALUES (431, 34, 'Sarıyer');
INSERT INTO `ilceler` VALUES (432, 34, 'Silivri');
INSERT INTO `ilceler` VALUES (433, 34, 'Şile');
INSERT INTO `ilceler` VALUES (434, 34, 'Şişli');
INSERT INTO `ilceler` VALUES (435, 34, 'Üsküdar');
INSERT INTO `ilceler` VALUES (436, 34, 'Zeytinburnu');
INSERT INTO `ilceler` VALUES (437, 34, 'Büyükçekmece');
INSERT INTO `ilceler` VALUES (438, 34, 'Kağıthane');
INSERT INTO `ilceler` VALUES (439, 34, 'Küçükçekmece');
INSERT INTO `ilceler` VALUES (440, 34, 'Pendik');
INSERT INTO `ilceler` VALUES (441, 34, 'Ümraniye');
INSERT INTO `ilceler` VALUES (442, 34, 'Bayrampaşa');
INSERT INTO `ilceler` VALUES (443, 34, 'Avcılar');
INSERT INTO `ilceler` VALUES (444, 34, 'Bağcılar');
INSERT INTO `ilceler` VALUES (445, 34, 'Bahçelievler');
INSERT INTO `ilceler` VALUES (446, 34, 'Güngören');
INSERT INTO `ilceler` VALUES (447, 34, 'Maltepe');
INSERT INTO `ilceler` VALUES (448, 34, 'Sultanbeyli');
INSERT INTO `ilceler` VALUES (449, 34, 'Tuzla');
INSERT INTO `ilceler` VALUES (450, 34, 'Esenler');
INSERT INTO `ilceler` VALUES (451, 34, 'Arnavutköy');
INSERT INTO `ilceler` VALUES (452, 34, 'Ataşehir');
INSERT INTO `ilceler` VALUES (453, 34, 'Başakşehir');
INSERT INTO `ilceler` VALUES (454, 34, 'Beylikdüzü');
INSERT INTO `ilceler` VALUES (455, 34, 'Çekmeköy');
INSERT INTO `ilceler` VALUES (456, 34, 'Esenyurt');
INSERT INTO `ilceler` VALUES (457, 34, 'Sancaktepe');
INSERT INTO `ilceler` VALUES (458, 34, 'Sultangazi');
INSERT INTO `ilceler` VALUES (459, 35, 'Aliağa');
INSERT INTO `ilceler` VALUES (460, 35, 'Bayındır');
INSERT INTO `ilceler` VALUES (461, 35, 'Bergama');
INSERT INTO `ilceler` VALUES (462, 35, 'Bornova');
INSERT INTO `ilceler` VALUES (463, 35, 'Çeşme');
INSERT INTO `ilceler` VALUES (464, 35, 'Dikili');
INSERT INTO `ilceler` VALUES (465, 35, 'Foça');
INSERT INTO `ilceler` VALUES (466, 35, 'Karaburun');
INSERT INTO `ilceler` VALUES (467, 35, 'Karşıyaka');
INSERT INTO `ilceler` VALUES (468, 35, 'Kemalpaşa');
INSERT INTO `ilceler` VALUES (469, 35, 'Kınık');
INSERT INTO `ilceler` VALUES (470, 35, 'Kiraz');
INSERT INTO `ilceler` VALUES (471, 35, 'Menemen');
INSERT INTO `ilceler` VALUES (472, 35, 'Ödemiş');
INSERT INTO `ilceler` VALUES (473, 35, 'Seferihisar');
INSERT INTO `ilceler` VALUES (474, 35, 'Selçuk');
INSERT INTO `ilceler` VALUES (475, 35, 'Tire');
INSERT INTO `ilceler` VALUES (476, 35, 'Torbalı');
INSERT INTO `ilceler` VALUES (477, 35, 'Urla');
INSERT INTO `ilceler` VALUES (478, 35, 'Beydağ');
INSERT INTO `ilceler` VALUES (479, 35, 'Buca');
INSERT INTO `ilceler` VALUES (480, 35, 'Konak');
INSERT INTO `ilceler` VALUES (481, 35, 'Menderes');
INSERT INTO `ilceler` VALUES (482, 35, 'Balçova');
INSERT INTO `ilceler` VALUES (483, 35, 'Çiğli');
INSERT INTO `ilceler` VALUES (484, 35, 'Gaziemir');
INSERT INTO `ilceler` VALUES (485, 35, 'Narlıdere');
INSERT INTO `ilceler` VALUES (486, 35, 'Güzelbahçe');
INSERT INTO `ilceler` VALUES (487, 35, 'Bayraklı');
INSERT INTO `ilceler` VALUES (488, 35, 'Karabağlar');
INSERT INTO `ilceler` VALUES (489, 36, 'Arpaçay');
INSERT INTO `ilceler` VALUES (490, 36, 'Digor');
INSERT INTO `ilceler` VALUES (491, 36, 'Kağızman');
INSERT INTO `ilceler` VALUES (492, 36, 'Kars Merkez');
INSERT INTO `ilceler` VALUES (493, 36, 'Sarıkamış');
INSERT INTO `ilceler` VALUES (494, 36, 'Selim');
INSERT INTO `ilceler` VALUES (495, 36, 'Susuz');
INSERT INTO `ilceler` VALUES (496, 36, 'Akyaka');
INSERT INTO `ilceler` VALUES (497, 37, 'Abana');
INSERT INTO `ilceler` VALUES (498, 37, 'Araç');
INSERT INTO `ilceler` VALUES (499, 37, 'Azdavay');
INSERT INTO `ilceler` VALUES (500, 37, 'Bozkurt / Kastamonu');
INSERT INTO `ilceler` VALUES (501, 37, 'Cide');
INSERT INTO `ilceler` VALUES (502, 37, 'Çatalzeytin');
INSERT INTO `ilceler` VALUES (503, 37, 'Daday');
INSERT INTO `ilceler` VALUES (504, 37, 'Devrekani');
INSERT INTO `ilceler` VALUES (505, 37, 'İnebolu');
INSERT INTO `ilceler` VALUES (506, 37, 'Kastamonu Merkez');
INSERT INTO `ilceler` VALUES (507, 37, 'Küre');
INSERT INTO `ilceler` VALUES (508, 37, 'Taşköprü');
INSERT INTO `ilceler` VALUES (509, 37, 'Tosya');
INSERT INTO `ilceler` VALUES (510, 37, 'İhsangazi');
INSERT INTO `ilceler` VALUES (511, 37, 'Pınarbaşı / Kastamonu');
INSERT INTO `ilceler` VALUES (512, 37, 'Şenpazar');
INSERT INTO `ilceler` VALUES (513, 37, 'Ağlı');
INSERT INTO `ilceler` VALUES (514, 37, 'Doğanyurt');
INSERT INTO `ilceler` VALUES (515, 37, 'Hanönü');
INSERT INTO `ilceler` VALUES (516, 37, 'Seydiler');
INSERT INTO `ilceler` VALUES (517, 38, 'Bünyan');
INSERT INTO `ilceler` VALUES (518, 38, 'Develi');
INSERT INTO `ilceler` VALUES (519, 38, 'Felahiye');
INSERT INTO `ilceler` VALUES (520, 38, 'İncesu');
INSERT INTO `ilceler` VALUES (521, 38, 'Pınarbaşı / Kayseri');
INSERT INTO `ilceler` VALUES (522, 38, 'Sarıoğlan');
INSERT INTO `ilceler` VALUES (523, 38, 'Sarız');
INSERT INTO `ilceler` VALUES (524, 38, 'Tomarza');
INSERT INTO `ilceler` VALUES (525, 38, 'Yahyalı');
INSERT INTO `ilceler` VALUES (526, 38, 'Yeşilhisar');
INSERT INTO `ilceler` VALUES (527, 38, 'Akkışla');
INSERT INTO `ilceler` VALUES (528, 38, 'Talas');
INSERT INTO `ilceler` VALUES (529, 38, 'Kocasinan');
INSERT INTO `ilceler` VALUES (530, 38, 'Melikgazi');
INSERT INTO `ilceler` VALUES (531, 38, 'Hacılar');
INSERT INTO `ilceler` VALUES (532, 38, 'Özvatan');
INSERT INTO `ilceler` VALUES (533, 39, 'Babaeski');
INSERT INTO `ilceler` VALUES (534, 39, 'Demirköy');
INSERT INTO `ilceler` VALUES (535, 39, 'Kırklareli Merkez');
INSERT INTO `ilceler` VALUES (536, 39, 'Kofçaz');
INSERT INTO `ilceler` VALUES (537, 39, 'Lüleburgaz');
INSERT INTO `ilceler` VALUES (538, 39, 'Pehlivanköy');
INSERT INTO `ilceler` VALUES (539, 39, 'Pınarhisar');
INSERT INTO `ilceler` VALUES (540, 39, 'Vize');
INSERT INTO `ilceler` VALUES (541, 40, 'Çiçekdağı');
INSERT INTO `ilceler` VALUES (542, 40, 'Kaman');
INSERT INTO `ilceler` VALUES (543, 40, 'Kırşehir Merkez');
INSERT INTO `ilceler` VALUES (544, 40, 'Mucur');
INSERT INTO `ilceler` VALUES (545, 40, 'Akpınar');
INSERT INTO `ilceler` VALUES (546, 40, 'Akçakent');
INSERT INTO `ilceler` VALUES (547, 40, 'Boztepe');
INSERT INTO `ilceler` VALUES (548, 41, 'Gebze');
INSERT INTO `ilceler` VALUES (549, 41, 'Gölcük');
INSERT INTO `ilceler` VALUES (550, 41, 'Kandıra');
INSERT INTO `ilceler` VALUES (551, 41, 'Karamürsel');
INSERT INTO `ilceler` VALUES (552, 41, 'Körfez');
INSERT INTO `ilceler` VALUES (553, 41, 'Derince');
INSERT INTO `ilceler` VALUES (554, 41, 'Başiskele');
INSERT INTO `ilceler` VALUES (555, 41, 'Çayırova');
INSERT INTO `ilceler` VALUES (556, 41, 'Darıca');
INSERT INTO `ilceler` VALUES (557, 41, 'Dilovası');
INSERT INTO `ilceler` VALUES (558, 41, 'İzmit');
INSERT INTO `ilceler` VALUES (559, 41, 'Kartepe');
INSERT INTO `ilceler` VALUES (560, 42, 'Akşehir');
INSERT INTO `ilceler` VALUES (561, 42, 'Beyşehir');
INSERT INTO `ilceler` VALUES (562, 42, 'Bozkır');
INSERT INTO `ilceler` VALUES (563, 42, 'Cihanbeyli');
INSERT INTO `ilceler` VALUES (564, 42, 'Çumra');
INSERT INTO `ilceler` VALUES (565, 42, 'Doğanhisar');
INSERT INTO `ilceler` VALUES (566, 42, 'Ereğli / Konya');
INSERT INTO `ilceler` VALUES (567, 42, 'Hadim');
INSERT INTO `ilceler` VALUES (568, 42, 'Ilgın');
INSERT INTO `ilceler` VALUES (569, 42, 'Kadınhanı');
INSERT INTO `ilceler` VALUES (570, 42, 'Karapınar');
INSERT INTO `ilceler` VALUES (571, 42, 'Kulu');
INSERT INTO `ilceler` VALUES (572, 42, 'Sarayönü');
INSERT INTO `ilceler` VALUES (573, 42, 'Seydişehir');
INSERT INTO `ilceler` VALUES (574, 42, 'Yunak');
INSERT INTO `ilceler` VALUES (575, 42, 'Akören');
INSERT INTO `ilceler` VALUES (576, 42, 'Altınekin');
INSERT INTO `ilceler` VALUES (577, 42, 'Derebucak');
INSERT INTO `ilceler` VALUES (578, 42, 'Hüyük');
INSERT INTO `ilceler` VALUES (579, 42, 'Karatay');
INSERT INTO `ilceler` VALUES (580, 42, 'Meram');
INSERT INTO `ilceler` VALUES (581, 42, 'Selçuklu');
INSERT INTO `ilceler` VALUES (582, 42, 'Taşkent');
INSERT INTO `ilceler` VALUES (583, 42, 'Ahırlı');
INSERT INTO `ilceler` VALUES (584, 42, 'Çeltik');
INSERT INTO `ilceler` VALUES (585, 42, 'Derbent');
INSERT INTO `ilceler` VALUES (586, 42, 'Emirgazi');
INSERT INTO `ilceler` VALUES (587, 42, 'Güneysınır');
INSERT INTO `ilceler` VALUES (588, 42, 'Halkapınar');
INSERT INTO `ilceler` VALUES (589, 42, 'Tuzlukçu');
INSERT INTO `ilceler` VALUES (590, 42, 'Yalıhüyük');
INSERT INTO `ilceler` VALUES (591, 43, 'Altıntaş');
INSERT INTO `ilceler` VALUES (592, 43, 'Domaniç');
INSERT INTO `ilceler` VALUES (593, 43, 'Emet');
INSERT INTO `ilceler` VALUES (594, 43, 'Gediz');
INSERT INTO `ilceler` VALUES (595, 43, 'Kütahya Merkez');
INSERT INTO `ilceler` VALUES (596, 43, 'Simav');
INSERT INTO `ilceler` VALUES (597, 43, 'Tavşanlı');
INSERT INTO `ilceler` VALUES (598, 43, 'Aslanapa');
INSERT INTO `ilceler` VALUES (599, 43, 'Dumlupınar');
INSERT INTO `ilceler` VALUES (600, 43, 'Hisarcık');
INSERT INTO `ilceler` VALUES (601, 43, 'Şaphane');
INSERT INTO `ilceler` VALUES (602, 43, 'Çavdarhisar');
INSERT INTO `ilceler` VALUES (603, 43, 'Pazarlar');
INSERT INTO `ilceler` VALUES (604, 44, 'Akçadağ');
INSERT INTO `ilceler` VALUES (605, 44, 'Arapgir');
INSERT INTO `ilceler` VALUES (606, 44, 'Arguvan');
INSERT INTO `ilceler` VALUES (607, 44, 'Darende');
INSERT INTO `ilceler` VALUES (608, 44, 'Doğanşehir');
INSERT INTO `ilceler` VALUES (609, 44, 'Hekimhan');
INSERT INTO `ilceler` VALUES (610, 44, 'Pütürge');
INSERT INTO `ilceler` VALUES (611, 44, 'Yeşilyurt / Malatya');
INSERT INTO `ilceler` VALUES (612, 44, 'Battalgazi');
INSERT INTO `ilceler` VALUES (613, 44, 'Doğanyol');
INSERT INTO `ilceler` VALUES (614, 44, 'Kale / Malatya');
INSERT INTO `ilceler` VALUES (615, 44, 'Kuluncak');
INSERT INTO `ilceler` VALUES (616, 44, 'Yazıhan');
INSERT INTO `ilceler` VALUES (617, 45, 'Akhisar');
INSERT INTO `ilceler` VALUES (618, 45, 'Alaşehir');
INSERT INTO `ilceler` VALUES (619, 45, 'Demirci');
INSERT INTO `ilceler` VALUES (620, 45, 'Gördes');
INSERT INTO `ilceler` VALUES (621, 45, 'Kırkağaç');
INSERT INTO `ilceler` VALUES (622, 45, 'Kula');
INSERT INTO `ilceler` VALUES (623, 45, 'Salihli');
INSERT INTO `ilceler` VALUES (624, 45, 'Sarıgöl');
INSERT INTO `ilceler` VALUES (625, 45, 'Saruhanlı');
INSERT INTO `ilceler` VALUES (626, 45, 'Selendi');
INSERT INTO `ilceler` VALUES (627, 45, 'Soma');
INSERT INTO `ilceler` VALUES (628, 45, 'Turgutlu');
INSERT INTO `ilceler` VALUES (629, 45, 'Ahmetli');
INSERT INTO `ilceler` VALUES (630, 45, 'Gölmarmara');
INSERT INTO `ilceler` VALUES (631, 45, 'Köprübaşı / Manisa');
INSERT INTO `ilceler` VALUES (632, 45, 'Şehzadeler');
INSERT INTO `ilceler` VALUES (633, 45, 'Yunusemre');
INSERT INTO `ilceler` VALUES (634, 46, 'Afşin');
INSERT INTO `ilceler` VALUES (635, 46, 'Andırın');
INSERT INTO `ilceler` VALUES (636, 46, 'Elbistan');
INSERT INTO `ilceler` VALUES (637, 46, 'Göksun');
INSERT INTO `ilceler` VALUES (638, 46, 'Pazarcık');
INSERT INTO `ilceler` VALUES (639, 46, 'Türkoğlu');
INSERT INTO `ilceler` VALUES (640, 46, 'Çağlayancerit');
INSERT INTO `ilceler` VALUES (641, 46, 'Ekinözü');
INSERT INTO `ilceler` VALUES (642, 46, 'Nurhak');
INSERT INTO `ilceler` VALUES (643, 46, 'Dulkadiroğlu');
INSERT INTO `ilceler` VALUES (644, 46, 'Onikişubat');
INSERT INTO `ilceler` VALUES (645, 47, 'Derik');
INSERT INTO `ilceler` VALUES (646, 47, 'Kızıltepe');
INSERT INTO `ilceler` VALUES (647, 47, 'Mazıdağı');
INSERT INTO `ilceler` VALUES (648, 47, 'Midyat');
INSERT INTO `ilceler` VALUES (649, 47, 'Nusaybin');
INSERT INTO `ilceler` VALUES (650, 47, 'Ömerli');
INSERT INTO `ilceler` VALUES (651, 47, 'Savur');
INSERT INTO `ilceler` VALUES (652, 47, 'Dargeçit');
INSERT INTO `ilceler` VALUES (653, 47, 'Yeşilli');
INSERT INTO `ilceler` VALUES (654, 47, 'Artuklu');
INSERT INTO `ilceler` VALUES (655, 48, 'Bodrum');
INSERT INTO `ilceler` VALUES (656, 48, 'Datça');
INSERT INTO `ilceler` VALUES (657, 48, 'Fethiye');
INSERT INTO `ilceler` VALUES (658, 48, 'Köyceğiz');
INSERT INTO `ilceler` VALUES (659, 48, 'Marmaris');
INSERT INTO `ilceler` VALUES (660, 48, 'Milas');
INSERT INTO `ilceler` VALUES (661, 48, 'Ula');
INSERT INTO `ilceler` VALUES (662, 48, 'Yatağan');
INSERT INTO `ilceler` VALUES (663, 48, 'Dalaman');
INSERT INTO `ilceler` VALUES (664, 48, 'Ortaca');
INSERT INTO `ilceler` VALUES (665, 48, 'Kavaklıdere');
INSERT INTO `ilceler` VALUES (666, 48, 'Menteşe');
INSERT INTO `ilceler` VALUES (667, 48, 'Seydikemer');
INSERT INTO `ilceler` VALUES (668, 49, 'Bulanık');
INSERT INTO `ilceler` VALUES (669, 49, 'Malazgirt');
INSERT INTO `ilceler` VALUES (670, 49, 'Muş Merkez');
INSERT INTO `ilceler` VALUES (671, 49, 'Varto');
INSERT INTO `ilceler` VALUES (672, 49, 'Hasköy');
INSERT INTO `ilceler` VALUES (673, 49, 'Korkut');
INSERT INTO `ilceler` VALUES (674, 50, 'Avanos');
INSERT INTO `ilceler` VALUES (675, 50, 'Derinkuyu');
INSERT INTO `ilceler` VALUES (676, 50, 'Gülşehir');
INSERT INTO `ilceler` VALUES (677, 50, 'Hacıbektaş');
INSERT INTO `ilceler` VALUES (678, 50, 'Kozaklı');
INSERT INTO `ilceler` VALUES (679, 50, 'Nevşehir Merkez');
INSERT INTO `ilceler` VALUES (680, 50, 'Ürgüp');
INSERT INTO `ilceler` VALUES (681, 50, 'Acıgöl');
INSERT INTO `ilceler` VALUES (682, 51, 'Bor');
INSERT INTO `ilceler` VALUES (683, 51, 'Çamardı');
INSERT INTO `ilceler` VALUES (684, 51, 'Niğde Merkez');
INSERT INTO `ilceler` VALUES (685, 51, 'Ulukışla');
INSERT INTO `ilceler` VALUES (686, 51, 'Altunhisar');
INSERT INTO `ilceler` VALUES (687, 51, 'Çiftlik');
INSERT INTO `ilceler` VALUES (688, 52, 'Akkuş');
INSERT INTO `ilceler` VALUES (689, 52, 'Aybastı');
INSERT INTO `ilceler` VALUES (690, 52, 'Fatsa');
INSERT INTO `ilceler` VALUES (691, 52, 'Gölköy');
INSERT INTO `ilceler` VALUES (692, 52, 'Korgan');
INSERT INTO `ilceler` VALUES (693, 52, 'Kumru');
INSERT INTO `ilceler` VALUES (694, 52, 'Mesudiye');
INSERT INTO `ilceler` VALUES (695, 52, 'Perşembe');
INSERT INTO `ilceler` VALUES (696, 52, 'Ulubey / Ordu');
INSERT INTO `ilceler` VALUES (697, 52, 'Ünye');
INSERT INTO `ilceler` VALUES (698, 52, 'Gülyalı');
INSERT INTO `ilceler` VALUES (699, 52, 'Gürgentepe');
INSERT INTO `ilceler` VALUES (700, 52, 'Çamaş');
INSERT INTO `ilceler` VALUES (701, 52, 'Çatalpınar');
INSERT INTO `ilceler` VALUES (702, 52, 'Çaybaşı');
INSERT INTO `ilceler` VALUES (703, 52, 'İkizce');
INSERT INTO `ilceler` VALUES (704, 52, 'Kabadüz');
INSERT INTO `ilceler` VALUES (705, 52, 'Kabataş');
INSERT INTO `ilceler` VALUES (706, 52, 'Altınordu');
INSERT INTO `ilceler` VALUES (707, 53, 'Ardeşen');
INSERT INTO `ilceler` VALUES (708, 53, 'Çamlıhemşin');
INSERT INTO `ilceler` VALUES (709, 53, 'Çayeli');
INSERT INTO `ilceler` VALUES (710, 53, 'Fındıklı');
INSERT INTO `ilceler` VALUES (711, 53, 'İkizdere');
INSERT INTO `ilceler` VALUES (712, 53, 'Kalkandere');
INSERT INTO `ilceler` VALUES (713, 53, 'Pazar / Rize');
INSERT INTO `ilceler` VALUES (714, 53, 'Rize Merkez');
INSERT INTO `ilceler` VALUES (715, 53, 'Güneysu');
INSERT INTO `ilceler` VALUES (716, 53, 'Derepazarı');
INSERT INTO `ilceler` VALUES (717, 53, 'Hemşin');
INSERT INTO `ilceler` VALUES (718, 53, 'İyidere');
INSERT INTO `ilceler` VALUES (719, 54, 'Akyazı');
INSERT INTO `ilceler` VALUES (720, 54, 'Geyve');
INSERT INTO `ilceler` VALUES (721, 54, 'Hendek');
INSERT INTO `ilceler` VALUES (722, 54, 'Karasu');
INSERT INTO `ilceler` VALUES (723, 54, 'Kaynarca');
INSERT INTO `ilceler` VALUES (724, 54, 'Sapanca');
INSERT INTO `ilceler` VALUES (725, 54, 'Kocaali');
INSERT INTO `ilceler` VALUES (726, 54, 'Pamukova');
INSERT INTO `ilceler` VALUES (727, 54, 'Taraklı');
INSERT INTO `ilceler` VALUES (728, 54, 'Ferizli');
INSERT INTO `ilceler` VALUES (729, 54, 'Karapürçek');
INSERT INTO `ilceler` VALUES (730, 54, 'Söğütlü');
INSERT INTO `ilceler` VALUES (731, 54, 'Adapazarı');
INSERT INTO `ilceler` VALUES (732, 54, 'Arifiye');
INSERT INTO `ilceler` VALUES (733, 54, 'Erenler');
INSERT INTO `ilceler` VALUES (734, 54, 'Serdivan');
INSERT INTO `ilceler` VALUES (735, 55, 'Alaçam');
INSERT INTO `ilceler` VALUES (736, 55, 'Bafra');
INSERT INTO `ilceler` VALUES (737, 55, 'Çarşamba');
INSERT INTO `ilceler` VALUES (738, 55, 'Havza');
INSERT INTO `ilceler` VALUES (739, 55, 'Kavak');
INSERT INTO `ilceler` VALUES (740, 55, 'Ladik');
INSERT INTO `ilceler` VALUES (741, 55, 'Terme');
INSERT INTO `ilceler` VALUES (742, 55, 'Vezirköprü');
INSERT INTO `ilceler` VALUES (743, 55, 'Asarcık');
INSERT INTO `ilceler` VALUES (744, 55, '19 Mayıs');
INSERT INTO `ilceler` VALUES (745, 55, 'Salıpazarı');
INSERT INTO `ilceler` VALUES (746, 55, 'Tekkeköy');
INSERT INTO `ilceler` VALUES (747, 55, 'Ayvacık / Samsun');
INSERT INTO `ilceler` VALUES (748, 55, 'Yakakent');
INSERT INTO `ilceler` VALUES (749, 55, 'Atakum');
INSERT INTO `ilceler` VALUES (750, 55, 'Canik');
INSERT INTO `ilceler` VALUES (751, 55, 'İlkadım');
INSERT INTO `ilceler` VALUES (752, 56, 'Baykan');
INSERT INTO `ilceler` VALUES (753, 56, 'Eruh');
INSERT INTO `ilceler` VALUES (754, 56, 'Kurtalan');
INSERT INTO `ilceler` VALUES (755, 56, 'Pervari');
INSERT INTO `ilceler` VALUES (756, 56, 'Siirt Merkez');
INSERT INTO `ilceler` VALUES (757, 56, 'Şirvan');
INSERT INTO `ilceler` VALUES (758, 56, 'Tillo');
INSERT INTO `ilceler` VALUES (759, 57, 'Ayancık');
INSERT INTO `ilceler` VALUES (760, 57, 'Boyabat');
INSERT INTO `ilceler` VALUES (761, 57, 'Durağan');
INSERT INTO `ilceler` VALUES (762, 57, 'Erfelek');
INSERT INTO `ilceler` VALUES (763, 57, 'Gerze');
INSERT INTO `ilceler` VALUES (764, 57, 'Sinop Merkez');
INSERT INTO `ilceler` VALUES (765, 57, 'Türkeli');
INSERT INTO `ilceler` VALUES (766, 57, 'Dikmen');
INSERT INTO `ilceler` VALUES (767, 57, 'Saraydüzü');
INSERT INTO `ilceler` VALUES (768, 58, 'Divriği');
INSERT INTO `ilceler` VALUES (769, 58, 'Gemerek');
INSERT INTO `ilceler` VALUES (770, 58, 'Gürün');
INSERT INTO `ilceler` VALUES (771, 58, 'Hafik');
INSERT INTO `ilceler` VALUES (772, 58, 'İmranlı');
INSERT INTO `ilceler` VALUES (773, 58, 'Kangal');
INSERT INTO `ilceler` VALUES (774, 58, 'Koyulhisar');
INSERT INTO `ilceler` VALUES (775, 58, 'Sivas Merkez');
INSERT INTO `ilceler` VALUES (776, 58, 'Suşehri');
INSERT INTO `ilceler` VALUES (777, 58, 'Şarkışla');
INSERT INTO `ilceler` VALUES (778, 58, 'Yıldızeli');
INSERT INTO `ilceler` VALUES (779, 58, 'Zara');
INSERT INTO `ilceler` VALUES (780, 58, 'Akıncılar');
INSERT INTO `ilceler` VALUES (781, 58, 'Altınyayla / Sivas');
INSERT INTO `ilceler` VALUES (782, 58, 'Doğanşar');
INSERT INTO `ilceler` VALUES (783, 58, 'Gölova');
INSERT INTO `ilceler` VALUES (784, 58, 'Ulaş');
INSERT INTO `ilceler` VALUES (785, 59, 'Çerkezköy');
INSERT INTO `ilceler` VALUES (786, 59, 'Çorlu');
INSERT INTO `ilceler` VALUES (787, 59, 'Hayrabolu');
INSERT INTO `ilceler` VALUES (788, 59, 'Malkara');
INSERT INTO `ilceler` VALUES (789, 59, 'Muratlı');
INSERT INTO `ilceler` VALUES (790, 59, 'Saray / Tekirdağ');
INSERT INTO `ilceler` VALUES (791, 59, 'Şarköy');
INSERT INTO `ilceler` VALUES (792, 59, 'Marmaraereğlisi');
INSERT INTO `ilceler` VALUES (793, 59, 'Ergene');
INSERT INTO `ilceler` VALUES (794, 59, 'Süleymanpaşa');
INSERT INTO `ilceler` VALUES (795, 60, 'Almus');
INSERT INTO `ilceler` VALUES (796, 60, 'Artova');
INSERT INTO `ilceler` VALUES (797, 60, 'Erbaa');
INSERT INTO `ilceler` VALUES (798, 60, 'Niksar');
INSERT INTO `ilceler` VALUES (799, 60, 'Reşadiye');
INSERT INTO `ilceler` VALUES (800, 60, 'Tokat Merkez');
INSERT INTO `ilceler` VALUES (801, 60, 'Turhal');
INSERT INTO `ilceler` VALUES (802, 60, 'Zile');
INSERT INTO `ilceler` VALUES (803, 60, 'Pazar / Tokat');
INSERT INTO `ilceler` VALUES (804, 60, 'Yeşilyurt / Tokat');
INSERT INTO `ilceler` VALUES (805, 60, 'Başçiftlik');
INSERT INTO `ilceler` VALUES (806, 60, 'Sulusaray');
INSERT INTO `ilceler` VALUES (807, 61, 'Akçaabat');
INSERT INTO `ilceler` VALUES (808, 61, 'Araklı');
INSERT INTO `ilceler` VALUES (809, 61, 'Arsin');
INSERT INTO `ilceler` VALUES (810, 61, 'Çaykara');
INSERT INTO `ilceler` VALUES (811, 61, 'Maçka');
INSERT INTO `ilceler` VALUES (812, 61, 'Of');
INSERT INTO `ilceler` VALUES (813, 61, 'Sürmene');
INSERT INTO `ilceler` VALUES (814, 61, 'Tonya');
INSERT INTO `ilceler` VALUES (815, 61, 'Vakfıkebir');
INSERT INTO `ilceler` VALUES (816, 61, 'Yomra');
INSERT INTO `ilceler` VALUES (817, 61, 'Beşikdüzü');
INSERT INTO `ilceler` VALUES (818, 61, 'Şalpazarı');
INSERT INTO `ilceler` VALUES (819, 61, 'Çarşıbaşı');
INSERT INTO `ilceler` VALUES (820, 61, 'Dernekpazarı');
INSERT INTO `ilceler` VALUES (821, 61, 'Düzköy');
INSERT INTO `ilceler` VALUES (822, 61, 'Hayrat');
INSERT INTO `ilceler` VALUES (823, 61, 'Köprübaşı / Trabzon');
INSERT INTO `ilceler` VALUES (824, 61, 'Ortahisar');
INSERT INTO `ilceler` VALUES (825, 62, 'Çemişgezek');
INSERT INTO `ilceler` VALUES (826, 62, 'Hozat');
INSERT INTO `ilceler` VALUES (827, 62, 'Mazgirt');
INSERT INTO `ilceler` VALUES (828, 62, 'Nazımiye');
INSERT INTO `ilceler` VALUES (829, 62, 'Ovacık / Tunceli');
INSERT INTO `ilceler` VALUES (830, 62, 'Pertek');
INSERT INTO `ilceler` VALUES (831, 62, 'Pülümür');
INSERT INTO `ilceler` VALUES (832, 62, 'Tunceli Merkez');
INSERT INTO `ilceler` VALUES (833, 63, 'Akçakale');
INSERT INTO `ilceler` VALUES (834, 63, 'Birecik');
INSERT INTO `ilceler` VALUES (835, 63, 'Bozova');
INSERT INTO `ilceler` VALUES (836, 63, 'Ceylanpınar');
INSERT INTO `ilceler` VALUES (837, 63, 'Halfeti');
INSERT INTO `ilceler` VALUES (838, 63, 'Hilvan');
INSERT INTO `ilceler` VALUES (839, 63, 'Siverek');
INSERT INTO `ilceler` VALUES (840, 63, 'Suruç');
INSERT INTO `ilceler` VALUES (841, 63, 'Viranşehir');
INSERT INTO `ilceler` VALUES (842, 63, 'Harran');
INSERT INTO `ilceler` VALUES (843, 63, 'Eyyübiye');
INSERT INTO `ilceler` VALUES (844, 63, 'Haliliye');
INSERT INTO `ilceler` VALUES (845, 63, 'Karaköprü');
INSERT INTO `ilceler` VALUES (846, 64, 'Banaz');
INSERT INTO `ilceler` VALUES (847, 64, 'Eşme');
INSERT INTO `ilceler` VALUES (848, 64, 'Karahallı');
INSERT INTO `ilceler` VALUES (849, 64, 'Sivaslı');
INSERT INTO `ilceler` VALUES (850, 64, 'Ulubey / Uşak');
INSERT INTO `ilceler` VALUES (851, 64, 'Uşak Merkez');
INSERT INTO `ilceler` VALUES (852, 65, 'Başkale');
INSERT INTO `ilceler` VALUES (853, 65, 'Çatak');
INSERT INTO `ilceler` VALUES (854, 65, 'Erciş');
INSERT INTO `ilceler` VALUES (855, 65, 'Gevaş');
INSERT INTO `ilceler` VALUES (856, 65, 'Gürpınar');
INSERT INTO `ilceler` VALUES (857, 65, 'Muradiye');
INSERT INTO `ilceler` VALUES (858, 65, 'Özalp');
INSERT INTO `ilceler` VALUES (859, 65, 'Bahçesaray');
INSERT INTO `ilceler` VALUES (860, 65, 'Çaldıran');
INSERT INTO `ilceler` VALUES (861, 65, 'Edremit / Van');
INSERT INTO `ilceler` VALUES (862, 65, 'Saray / Van');
INSERT INTO `ilceler` VALUES (863, 65, 'İpekyolu');
INSERT INTO `ilceler` VALUES (864, 65, 'Tuşba');
INSERT INTO `ilceler` VALUES (865, 66, 'Akdağmadeni');
INSERT INTO `ilceler` VALUES (866, 66, 'Boğazlıyan');
INSERT INTO `ilceler` VALUES (867, 66, 'Çayıralan');
INSERT INTO `ilceler` VALUES (868, 66, 'Çekerek');
INSERT INTO `ilceler` VALUES (869, 66, 'Sarıkaya');
INSERT INTO `ilceler` VALUES (870, 66, 'Sorgun');
INSERT INTO `ilceler` VALUES (871, 66, 'Şefaatli');
INSERT INTO `ilceler` VALUES (872, 66, 'Yerköy');
INSERT INTO `ilceler` VALUES (873, 66, 'Yozgat Merkez');
INSERT INTO `ilceler` VALUES (874, 66, 'Aydıncık / Yozgat');
INSERT INTO `ilceler` VALUES (875, 66, 'Çandır');
INSERT INTO `ilceler` VALUES (876, 66, 'Kadışehri');
INSERT INTO `ilceler` VALUES (877, 66, 'Saraykent');
INSERT INTO `ilceler` VALUES (878, 66, 'Yenifakılı');
INSERT INTO `ilceler` VALUES (879, 67, 'Çaycuma');
INSERT INTO `ilceler` VALUES (880, 67, 'Devrek');
INSERT INTO `ilceler` VALUES (881, 67, 'Ereğli / Zonguldak');
INSERT INTO `ilceler` VALUES (882, 67, 'Zonguldak Merkez');
INSERT INTO `ilceler` VALUES (883, 67, 'Alaplı');
INSERT INTO `ilceler` VALUES (884, 67, 'Gökçebey');
INSERT INTO `ilceler` VALUES (885, 68, 'Aksaray Merkez');
INSERT INTO `ilceler` VALUES (886, 68, 'Ortaköy / Aksaray');
INSERT INTO `ilceler` VALUES (887, 68, 'Ağaçören');
INSERT INTO `ilceler` VALUES (888, 68, 'Güzelyurt');
INSERT INTO `ilceler` VALUES (889, 68, 'Sarıyahşi');
INSERT INTO `ilceler` VALUES (890, 68, 'Eskil');
INSERT INTO `ilceler` VALUES (891, 68, 'Gülağaç');
INSERT INTO `ilceler` VALUES (892, 69, 'Bayburt Merkez');
INSERT INTO `ilceler` VALUES (893, 69, 'Aydıntepe');
INSERT INTO `ilceler` VALUES (894, 69, 'Demirözü');
INSERT INTO `ilceler` VALUES (895, 70, 'Ermenek');
INSERT INTO `ilceler` VALUES (896, 70, 'Karaman Merkez');
INSERT INTO `ilceler` VALUES (897, 70, 'Ayrancı');
INSERT INTO `ilceler` VALUES (898, 70, 'Kazımkarabekir');
INSERT INTO `ilceler` VALUES (899, 70, 'Başyayla');
INSERT INTO `ilceler` VALUES (900, 70, 'Sarıveliler');
INSERT INTO `ilceler` VALUES (901, 71, 'Delice');
INSERT INTO `ilceler` VALUES (902, 71, 'Keskin');
INSERT INTO `ilceler` VALUES (903, 71, 'Kırıkkale Merkez');
INSERT INTO `ilceler` VALUES (904, 71, 'Sulakyurt');
INSERT INTO `ilceler` VALUES (905, 71, 'Bahşili');
INSERT INTO `ilceler` VALUES (906, 71, 'Balışeyh');
INSERT INTO `ilceler` VALUES (907, 71, 'Çelebi');
INSERT INTO `ilceler` VALUES (908, 71, 'Karakeçili');
INSERT INTO `ilceler` VALUES (909, 71, 'Yahşihan');
INSERT INTO `ilceler` VALUES (910, 72, 'Batman Merkez');
INSERT INTO `ilceler` VALUES (911, 72, 'Beşiri');
INSERT INTO `ilceler` VALUES (912, 72, 'Gercüş');
INSERT INTO `ilceler` VALUES (913, 72, 'Kozluk');
INSERT INTO `ilceler` VALUES (914, 72, 'Sason');
INSERT INTO `ilceler` VALUES (915, 72, 'Hasankeyf');
INSERT INTO `ilceler` VALUES (916, 73, 'Beytüşşebap');
INSERT INTO `ilceler` VALUES (917, 73, 'Cizre');
INSERT INTO `ilceler` VALUES (918, 73, 'İdil');
INSERT INTO `ilceler` VALUES (919, 73, 'Silopi');
INSERT INTO `ilceler` VALUES (920, 73, 'Şırnak Merkez');
INSERT INTO `ilceler` VALUES (921, 73, 'Uludere');
INSERT INTO `ilceler` VALUES (922, 73, 'Güçlükonak');
INSERT INTO `ilceler` VALUES (923, 74, 'Bartın Merkez');
INSERT INTO `ilceler` VALUES (924, 74, 'Kurucaşile');
INSERT INTO `ilceler` VALUES (925, 74, 'Ulus');
INSERT INTO `ilceler` VALUES (926, 74, 'Amasra');
INSERT INTO `ilceler` VALUES (927, 75, 'Ardahan Merkez');
INSERT INTO `ilceler` VALUES (928, 75, 'Çıldır');
INSERT INTO `ilceler` VALUES (929, 75, 'Göle');
INSERT INTO `ilceler` VALUES (930, 75, 'Hanak');
INSERT INTO `ilceler` VALUES (931, 75, 'Posof');
INSERT INTO `ilceler` VALUES (932, 75, 'Damal');
INSERT INTO `ilceler` VALUES (933, 76, 'Aralık');
INSERT INTO `ilceler` VALUES (934, 76, 'Iğdır Merkez');
INSERT INTO `ilceler` VALUES (935, 76, 'Tuzluca');
INSERT INTO `ilceler` VALUES (936, 76, 'Karakoyunlu');
INSERT INTO `ilceler` VALUES (937, 77, 'Yalova Merkez');
INSERT INTO `ilceler` VALUES (938, 77, 'Altınova');
INSERT INTO `ilceler` VALUES (939, 77, 'Armutlu');
INSERT INTO `ilceler` VALUES (940, 77, 'Çınarcık');
INSERT INTO `ilceler` VALUES (941, 77, 'Çiftlikköy');
INSERT INTO `ilceler` VALUES (942, 77, 'Termal');
INSERT INTO `ilceler` VALUES (943, 78, 'Eflani');
INSERT INTO `ilceler` VALUES (944, 78, 'Eskipazar');
INSERT INTO `ilceler` VALUES (945, 78, 'Karabük Merkez');
INSERT INTO `ilceler` VALUES (946, 78, 'Ovacık / Karabük');
INSERT INTO `ilceler` VALUES (947, 78, 'Safranbolu');
INSERT INTO `ilceler` VALUES (948, 78, 'Yenice / Karabük');
INSERT INTO `ilceler` VALUES (949, 79, 'Kilis Merkez');
INSERT INTO `ilceler` VALUES (950, 79, 'Elbeyli');
INSERT INTO `ilceler` VALUES (951, 79, 'Musabeyli');
INSERT INTO `ilceler` VALUES (952, 79, 'Polateli');
INSERT INTO `ilceler` VALUES (953, 80, 'Bahçe');
INSERT INTO `ilceler` VALUES (954, 80, 'Kadirli');
INSERT INTO `ilceler` VALUES (955, 80, 'Osmaniye Merkez');
INSERT INTO `ilceler` VALUES (956, 80, 'Düziçi');
INSERT INTO `ilceler` VALUES (957, 80, 'Hasanbeyli');
INSERT INTO `ilceler` VALUES (958, 80, 'Sumbas');
INSERT INTO `ilceler` VALUES (959, 80, 'Toprakkale');
INSERT INTO `ilceler` VALUES (960, 81, 'Akçakoca');
INSERT INTO `ilceler` VALUES (961, 81, 'Düzce Merkez');
INSERT INTO `ilceler` VALUES (962, 81, 'Yığılca');
INSERT INTO `ilceler` VALUES (963, 81, 'Cumayeri');
INSERT INTO `ilceler` VALUES (964, 81, 'Gölyaka');
INSERT INTO `ilceler` VALUES (965, 81, 'Çilimli');
INSERT INTO `ilceler` VALUES (966, 81, 'Gümüşova');
INSERT INTO `ilceler` VALUES (967, 81, 'Kaynaşlı');
COMMIT;

-- ----------------------------
-- Table structure for iller
-- ----------------------------
DROP TABLE IF EXISTS `iller`;
CREATE TABLE `iller` (
  `il_id` tinyint(3) unsigned NOT NULL AUTO_INCREMENT,
  `il_adi` char(40) NOT NULL,
  PRIMARY KEY (`il_id`),
  UNIQUE KEY `il_id` (`il_id`) USING BTREE
) ENGINE=MyISAM AUTO_INCREMENT=82 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of iller
-- ----------------------------
BEGIN;
INSERT INTO `iller` VALUES (1, 'Adana');
INSERT INTO `iller` VALUES (2, 'Adıyaman');
INSERT INTO `iller` VALUES (3, 'Afyonkarahisar');
INSERT INTO `iller` VALUES (4, 'Ağrı');
INSERT INTO `iller` VALUES (5, 'Amasya');
INSERT INTO `iller` VALUES (6, 'Ankara');
INSERT INTO `iller` VALUES (7, 'Antalya');
INSERT INTO `iller` VALUES (8, 'Artvin');
INSERT INTO `iller` VALUES (9, 'Aydın');
INSERT INTO `iller` VALUES (10, 'Balıkesir');
INSERT INTO `iller` VALUES (11, 'Bilecik');
INSERT INTO `iller` VALUES (12, 'Bingöl');
INSERT INTO `iller` VALUES (13, 'Bitlis');
INSERT INTO `iller` VALUES (14, 'Bolu');
INSERT INTO `iller` VALUES (15, 'Burdur');
INSERT INTO `iller` VALUES (16, 'Bursa');
INSERT INTO `iller` VALUES (17, 'Çanakkale');
INSERT INTO `iller` VALUES (18, 'Çankırı');
INSERT INTO `iller` VALUES (19, 'Çorum');
INSERT INTO `iller` VALUES (20, 'Denizli');
INSERT INTO `iller` VALUES (21, 'Diyarbakır');
INSERT INTO `iller` VALUES (22, 'Edirne');
INSERT INTO `iller` VALUES (23, 'Elazığ');
INSERT INTO `iller` VALUES (24, 'Erzincan');
INSERT INTO `iller` VALUES (25, 'Erzurum');
INSERT INTO `iller` VALUES (26, 'Eskişehir');
INSERT INTO `iller` VALUES (27, 'Gaziantep');
INSERT INTO `iller` VALUES (28, 'Giresun');
INSERT INTO `iller` VALUES (29, 'Gümüşhane');
INSERT INTO `iller` VALUES (30, 'Hakkari');
INSERT INTO `iller` VALUES (31, 'Hatay');
INSERT INTO `iller` VALUES (32, 'Isparta');
INSERT INTO `iller` VALUES (33, 'Mersin');
INSERT INTO `iller` VALUES (34, 'İstanbul');
INSERT INTO `iller` VALUES (35, 'İzmir');
INSERT INTO `iller` VALUES (36, 'Kars');
INSERT INTO `iller` VALUES (37, 'Kastamonu');
INSERT INTO `iller` VALUES (38, 'Kayseri');
INSERT INTO `iller` VALUES (39, 'Kırklareli');
INSERT INTO `iller` VALUES (40, 'Kırşehir');
INSERT INTO `iller` VALUES (41, 'Kocaeli');
INSERT INTO `iller` VALUES (42, 'Konya');
INSERT INTO `iller` VALUES (43, 'Kütahya');
INSERT INTO `iller` VALUES (44, 'Malatya');
INSERT INTO `iller` VALUES (45, 'Manisa');
INSERT INTO `iller` VALUES (46, 'Kahramanmaraş');
INSERT INTO `iller` VALUES (47, 'Mardin');
INSERT INTO `iller` VALUES (48, 'Muğla');
INSERT INTO `iller` VALUES (49, 'Muş');
INSERT INTO `iller` VALUES (50, 'Nevşehir');
INSERT INTO `iller` VALUES (51, 'Niğde');
INSERT INTO `iller` VALUES (52, 'Ordu');
INSERT INTO `iller` VALUES (53, 'Rize');
INSERT INTO `iller` VALUES (54, 'Sakarya');
INSERT INTO `iller` VALUES (55, 'Samsun');
INSERT INTO `iller` VALUES (56, 'Siirt');
INSERT INTO `iller` VALUES (57, 'Sinop');
INSERT INTO `iller` VALUES (58, 'Sivas');
INSERT INTO `iller` VALUES (59, 'Tekirdağ');
INSERT INTO `iller` VALUES (60, 'Tokat');
INSERT INTO `iller` VALUES (61, 'Trabzon');
INSERT INTO `iller` VALUES (62, 'Tunceli');
INSERT INTO `iller` VALUES (63, 'Şanlıurfa');
INSERT INTO `iller` VALUES (64, 'Uşak');
INSERT INTO `iller` VALUES (65, 'Van');
INSERT INTO `iller` VALUES (66, 'Yozgat');
INSERT INTO `iller` VALUES (67, 'Zonguldak');
INSERT INTO `iller` VALUES (68, 'Aksaray');
INSERT INTO `iller` VALUES (69, 'Bayburt');
INSERT INTO `iller` VALUES (70, 'Karaman');
INSERT INTO `iller` VALUES (71, 'Kırıkkale');
INSERT INTO `iller` VALUES (72, 'Batman');
INSERT INTO `iller` VALUES (73, 'Şırnak');
INSERT INTO `iller` VALUES (74, 'Bartın');
INSERT INTO `iller` VALUES (75, 'Ardahan');
INSERT INTO `iller` VALUES (76, 'Iğdır');
INSERT INTO `iller` VALUES (77, 'Yalova');
INSERT INTO `iller` VALUES (78, 'Karabük');
INSERT INTO `iller` VALUES (79, 'Kilis');
INSERT INTO `iller` VALUES (80, 'Osmaniye');
INSERT INTO `iller` VALUES (81, 'Düzce');
COMMIT;

-- ----------------------------
-- View structure for il_ilce_view
-- ----------------------------
DROP VIEW IF EXISTS `il_ilce_view`;
CREATE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `il_ilce_view` AS select `il`.`il_id` AS `il_id`,`il`.`il_adi` AS `il_adi`,`ilce`.`ilce_id` AS `ilce_id`,`ilce`.`ilce_adi` AS `ilce_adi` from (`iller` `il` left join `ilceler` `ilce` on((`il`.`il_id` = `ilce`.`il_id_fk`)));

SET FOREIGN_KEY_CHECKS = 1;
